# Welcome to Jekyll!
#
# This project is meant to auto generate a simple website with schema.org seo metadata.
#
# This config file is meant for settings that affect your whole dataset.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#
# Fill out dataset variables below
#
author:
  name: Quinn Hart
  email: qjhart@ucdavis.edu
keywords:
  - 
genre: Spatial Data
publisher:
  name: University of California, Davis
  url: https://www.library.ucdavis.edu
  description: Supporting research, teaching and learning in every discipline, the UC Davis Library is the academic heart of the university.
# ISO formatted, ex: "2016-03-09T17:27:20.578Z" 
datePublished: 2015-02-15

# Build settings
markdown: kramdown
theme: minima
